spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1185388058991241
            client-secret: 192d3c5cbf19e4abaceb5199ae033ada
            scope:
              - email
              - public_profile